# T012 - Q15: web-moon Deployment in moon
# Deployment will be in Pending state waiting for ConfigMap
# User must create the ConfigMap to make it work
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-moon
  namespace: moon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-moon
  template:
    metadata:
      labels:
        app: web-moon
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.3-alpine
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: configmap-web-moon-html
