# T017 - Q22: 16 pods with various labels in sun namespace
# User must add labels and annotations to specific pods
---
apiVersion: v1
kind: Pod
metadata:
  name: "0509649a"
  namespace: sun
  labels:
    type: runner
    type_old: messenger
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "0509649b"
  namespace: sun
  labels:
    type: worker
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "1428721e"
  namespace: sun
  labels:
    type: worker
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "1428721f"
  namespace: sun
  labels:
    type: worker
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "43b9a"
  namespace: sun
  labels:
    type: test
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "4c09"
  namespace: sun
  labels:
    type: worker
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "4c35"
  namespace: sun
  labels:
    type: worker
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "4fe4"
  namespace: sun
  labels:
    type: worker
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "5555a"
  namespace: sun
  labels:
    type: messenger
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "86cda"
  namespace: sun
  labels:
    type: runner
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "8d1c"
  namespace: sun
  labels:
    type: messenger
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "a004a"
  namespace: sun
  labels:
    type: runner
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "a94128196"
  namespace: sun
  labels:
    type: runner
    type_old: messenger
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "afd79200c56a"
  namespace: sun
  labels:
    type: worker
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "b667"
  namespace: sun
  labels:
    type: worker
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
---
apiVersion: v1
kind: Pod
metadata:
  name: "fdb2"
  namespace: sun
  labels:
    type: worker
spec:
  containers:
  - name: pod
    image: busybox:1.31.0
    command: ['sh', '-c', 'sleep 1d']
