# CKAD Simulation 3 - Dojo Byakko - Namespaces
# Tiger/predator themed namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: tiger
  labels:
    exam: ckad-simulation3
    theme: byakko
---
apiVersion: v1
kind: Namespace
metadata:
  name: claw
  labels:
    exam: ckad-simulation3
    theme: byakko
---
apiVersion: v1
kind: Namespace
metadata:
  name: stripe
  labels:
    exam: ckad-simulation3
    theme: byakko
---
apiVersion: v1
kind: Namespace
metadata:
  name: prowl
  labels:
    exam: ckad-simulation3
    theme: byakko
---
apiVersion: v1
kind: Namespace
metadata:
  name: hunt
  labels:
    exam: ckad-simulation3
    theme: byakko
---
apiVersion: v1
kind: Namespace
metadata:
  name: jungle
  labels:
    exam: ckad-simulation3
    theme: byakko
    name: jungle
---
apiVersion: v1
kind: Namespace
metadata:
  name: fang
  labels:
    exam: ckad-simulation3
    theme: byakko
---
apiVersion: v1
kind: Namespace
metadata:
  name: pounce
  labels:
    exam: ckad-simulation3
    theme: byakko
---
apiVersion: v1
kind: Namespace
metadata:
  name: stalker
  labels:
    exam: ckad-simulation3
    theme: byakko
---
apiVersion: v1
kind: Namespace
metadata:
  name: predator
  labels:
    exam: ckad-simulation3
    theme: byakko
