# Q19 - Pod for annotations exercise
apiVersion: v1
kind: Pod
metadata:
  name: lightning-pod
  namespace: zeus
  labels:
    app: lightning
spec:
  containers:
  - name: lightning-container
    image: nginx:1.21-alpine
    ports:
    - containerPort: 80
