# Q13 - Service for Ingress exercise
apiVersion: v1
kind: Service
metadata:
  name: radiance-svc
  namespace: baldur
spec:
  selector:
    app: radiance
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: radiance-pod
  namespace: baldur
  labels:
    app: radiance
spec:
  containers:
  - name: radiance
    image: nginx:1.21-alpine
    ports:
    - containerPort: 80
