# Q14 - Deployment for NodePort service exercise
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainbow-bridge
  namespace: asgard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bifrost
  template:
    metadata:
      labels:
        app: bifrost
    spec:
      containers:
      - name: bridge
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
