# T009 - Q8: Broken Deployment api-new-c32
# Has typo in image name: ngnix instead of nginx
# User must fix and scale to 3 replicas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-new-c32
  namespace: neptune
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-new-c32
  template:
    metadata:
      labels:
        app: api-new-c32
    spec:
      containers:
      - name: nginx
        image: ngnix:1.25.5-alpine
