# T011 - Q14: secret-handler Pod in moon
# User must create secrets and mount them
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-handler
  namespace: moon
  labels:
    id: secret-handler
    uuid: 1428721e-8d1c-4571-a2e2-01b5c9a6a134
spec:
  containers:
  - name: secret-handler
    image: bash:5.0.11
    args: ['bash', '-c', 'sleep 2d']
    volumeMounts:
    - name: cache-volume1
      mountPath: /cache1
    - name: cache-volume2
      mountPath: /cache2
    - name: cache-volume3
      mountPath: /cache3
    env:
    - name: SECRET_KEY_1
      value: ">8$kH#kj..i8}HImQd{"
    - name: SECRET_KEY_2
      value: "IO=a4L/XkRdvN8jM=Y+"
    - name: SECRET_KEY_3
      value: "-7PA0_Z]>{pwa43r)__"
  volumes:
  - name: cache-volume1
    emptyDir: {}
  - name: cache-volume2
    emptyDir: {}
  - name: cache-volume3
    emptyDir: {}
