# T014 - Q18: manager-api-deployment and broken Service in mars
# Service has wrong selector - user must fix it
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-api-deployment
  namespace: mars
spec:
  replicas: 4
  selector:
    matchLabels:
      id: manager-api-pod
  template:
    metadata:
      labels:
        id: manager-api-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.3-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: manager-api-svc
  namespace: mars
spec:
  selector:
    id: manager-api-deployment
  ports:
  - port: 4444
    targetPort: 80
