# T015 - Q19: jupiter-crew-deploy and Service in jupiter
# User must change Service to NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupiter-crew-deploy
  namespace: jupiter
spec:
  replicas: 1
  selector:
    matchLabels:
      id: jupiter-crew
  template:
    metadata:
      labels:
        id: jupiter-crew
    spec:
      containers:
      - name: httpd
        image: httpd:2.4-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: jupiter-crew-svc
  namespace: jupiter
spec:
  type: ClusterIP
  selector:
    id: jupiter-crew
  ports:
  - port: 8080
    targetPort: 80
