# Q4: Pre-existing deployment to be scaled
apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-app
  namespace: pegasus
  labels:
    app: star-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: star-app
  template:
    metadata:
      labels:
        app: star-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
