# Q16 - ServiceAccount for projected token question
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fire-sa
  namespace: magma
  labels:
    exam: ckad-simulation2
automountServiceAccountToken: false
