# Q16: Pre-existing ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: galaxy-sa
  namespace: cygnus
---
apiVersion: v1
kind: Secret
metadata:
  name: galaxy-sa-token
  namespace: cygnus
  annotations:
    kubernetes.io/service-account.name: galaxy-sa
type: kubernetes.io/service-account-token
